---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10005
mongodb:
  host: eobdb
  port: 27017
  username: eobuser
  password: eobuserpass
  auth_db: eob_system
  database: eob_system
  collection: accounts